### ISSUE TITLE
Using GPU to compress/convert?

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [Admirativ/Fallout4-Texture-Compressor#3]
Checking out https://github.com/Microsoft/DirectXTex/wiki/Texconv , there's an option to use the GPU, which is vastly superior in terms of parallelism, 

> -gpu adapterIndex: When compressing BC6H / BC7 content, texconv will use DirectCompute on the GPU at the given index if available. The default is 0 which is the default adapter.

Any way to add this option to test if it's better?

**Comment by Admirativ** [comment]
"The default is 0 which is the default adapter."
It already uses this option even if you don't specify it.
The only thing that matters is adapter. It will only be useful for people who have one less powerful gpu and one more powerful. So it would be better for them to specify to use better gpu if it is not default for some reason.

And I don't know would it worth the time it'll consume to implement that feature.
